# Generated by Django 4.2.13 on 2025-10-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='farmer',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
